version: '3.1'

services:
    postgres:
        image: postgres:12
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: bookdb
        ports:
            - '5432:5432'

    bookapi:
        build: .
        image: bookapi
        # command: dockerize -wait tcp://postgres:5432 -timeout 30s
        command: 'npm start'
        environment:
            DB_CONNECTION_STRING: postgres://postgres:1234@postgres:5432/bookdb
            SEED_DB: true
            PORT: 9595
        ports:
            - '9595:9595'
        depends_on:
            - postgres
